name: undefined

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
        - ./.env.prod
    ports:
      - "8094:8094"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: mikhalexandr
      POSTGRES_PASSWORD: phptop123
      POSTGRES_DB: etalon
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgres/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/var/lib/redis/data
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5


volumes:
  postgres_data:
  redis_data:
